export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';
export const GET_VIVEPORT_INITIATE = 'GET_VIVEPORT_INITIATE';
export const GET_VIVEPORT_SUCCESS = 'GET_VIVEPORT_SUCCESS';
export const GET_VIVEPORT_FAIL = 'GET_VIVEPORT_FAIL';
export const CHANGE_ACCOUNT_ID = 'CHANGE_ACCOUNT_ID';
